#!/usr/bin/env bash

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim
alias edit=nvim

# pyenv
export PATH="${HOME}/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# aliases

## Colorize the ls output ##
alias ls='ls -h --color=auto'

## Use a long listing format ##
alias ll='ls -la'

## Show hidden files ##
alias la='ls -d .*'

## Colorize the grep command output for ease of use
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

## Make parent directories on demand
alias mkdir='mkdir -pv'

# Starship prompt
eval "$(starship init bash)"
