#!/usr/bin/env bash

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim

# pyenv
export PATH="${HOME}/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Starship prompt
eval "$(starship init bash)"
