#!/usr/bin/env bash

# Editor
export EDITOR=nvim
export VISUAL=nvim
alias vim=nvim

# pyenv
export PATH="${HOME}/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# aliases

## Colorize the ls output ##
alias ls='ls --color=auto'

## Use a long listing format ##
alias ll='ls -la'

# Starship prompt
eval "$(starship init bash)"
